### ISSUE TITLE
New!! Current directory does not seem to be a valid Flutter Project directory

### ISSUE THREAD

**Issue by ChivialK** [ChinaStyle812/AssetsRefGenerator#15]
<img width="728" alt="截圖 2022-06-07 下午2 00 43" src="https://user-images.githubusercontent.com/8535276/172307378-d3f3bd6f-94bd-4604-81ab-fb7054ead168.png">

Cannot work on Android Studio Chipmunk 2021.2.1
Is there any other way to execute the script, like a command line or any folder path I can replace to make this work again?

**Comment by yxwandroid** [comment]
I have the same problem

**Comment by juanxme** [comment]
x2

**Comment by alok2811** [comment]
I have the same problem one solve it ..?

**Comment by AndrewShen812** [comment]
> I have the same problem one solve it ..?

@alok2811 I've published the v1.2.0 on Jan 03, 2023, which fixed this issue by ignoring .packages and pubspec.lock file check. If you're sure you're using v1.2.0 and having the same problem, can you post a demo project that reproduces this problem? I'll check it.

**Comment by AndrewShen812** [comment]
> I have the same problem one solve it ..?

@alok2811 I've published the v1.2.0 on Jan 03, 2023, which fixed this issue by ignoring .packages and pubspec.lock file check. If you're sure you're using v1.2.0 and having the same problem, can you post a demo project that reproduces this problem? I'll check it.

**Comment by alok2811** [comment]
@AndrewShen812 thank you buddy for your response but in Android studio it's version is v1.1.0 please update it then i will able to use it

![IMG_20230202_125350.jpg](https://user-images.githubusercontent.com/72010020/216258476-89075c54-7c6a-4604-a43e-601ceb486101.jpg)

**Comment by AndrewShen812** [comment]
> @AndrewShen812 thank you buddy for your response but in Android studio it's version is v1.1.0 please update it then i will able to use it
> 
> ![IMG_20230202_125350.jpg](https://user-images.githubusercontent.com/72010020/216258476-89075c54-7c6a-4604-a43e-601ceb486101.jpg)

@alok2811 I don't know why there's no update tips in your Android Studio😅, but I can get the update tips in Android Studio(Dolphin | 2021.3.1 Patch 1, Build #AI-213.7172.25.2113.9123335) on my MacBook.
<img width="995" alt="image" src="https://user-images.githubusercontent.com/12847396/216261139-9b708b4a-e31b-4a66-8f17-ad87bcf2db5f.png">
But you can still download the latest plugin zip file on [Releases page][1], and click "Install Plugin from Disk..." to install.

[1]: https://github.com/AndrewShen812/AssetsRefGenerator/releases

**Comment by alok2811** [comment]
> > @AndrewShen812 thank you buddy for your response but in Android studio it's version is v1.1.0 please update it then i will able to use it
> > 
> > ![IMG_20230202_125350.jpg](https://user-images.githubusercontent.com/72010020/216258476-89075c54-7c6a-4604-a43e-601ceb486101.jpg)
> 
> @alok2811 I don't know why there's no update tips in your Android Studio😅, but I can get the update tips in Android Studio(Dolphin | 2021.3.1 Patch 1, Build #AI-213.7172.25.2113.9123335) on my MacBook.
> <img width="995" alt="image" src="https://user-images.githubusercontent.com/12847396/216261139-9b708b4a-e31b-4a66-8f17-ad87bcf2db5f.png">
> But you can still download the latest plugin zip file on [Releases page][1], and click "Install Plugin from Disk..." to install.
> 
> [1]: https://github.com/AndrewShen812/AssetsRefGenerator/releases
> 

I am using the latest Android Studio Electric Ele | 2022.1.1 Patch 1 but it's still showing the old version.

![IMG_20230202_133529.jpg](https://user-images.githubusercontent.com/72010020/216266552-f4f598d2-fd47-4dab-abd4-0492b4fe6ec7.jpg)

**Comment by alok2811** [comment]
Hello, @AndrewShen812 I try to install using a zip file and identify the error check the screenshot and please resolve it ASAP. I am waiting for your positive response

<img width="1440" alt="Screenshot 2023-02-03 at 7 31 52 AM" src="https://user-images.githubusercontent.com/72010020/216494897-58abf942-f2c2-4508-8216-3f3cc8730f30.png">

**Comment by AndrewShen812** [comment]
> Hello, @AndrewShen812 I try to install using a zip file and identify the error check the screenshot and please resolve it ASAP. I am waiting for your positive response
> 
> <img alt="Screenshot 2023-02-03 at 7 31 52 AM" width="1440" src="https://user-images.githubusercontent.com/72010020/216494897-58abf942-f2c2-4508-8216-3f3cc8730f30.png">

I See. Could you please post your Android Studio version information? I'll have a try on the same version.

**Comment by alok2811** [comment]
![Screenshot 2023-02-03 at 10 29 35 AM](https://user-images.githubusercontent.com/72010020/216516270-0ef095cf-2d36-4740-80f7-b9e0314c7f66.png)

Using latest version of Android Studio

**Comment by AndrewShen812** [comment]
> ![Screenshot 2023-02-03 at 10 29 35 AM](https://user-images.githubusercontent.com/72010020/216516270-0ef095cf-2d36-4740-80f7-b9e0314c7f66.png)
> 
> Using latest version of Android Studio

Sorry for the wait，I‘ve published v1.2.221, which is compatible for IDEA 2022.1.4(Build 221.6008.13) and Android Studio Electric Eel. It has been approved by JetBrains , you can also get it on the [Releases page][1].

[1]: https://github.com/AndrewShen812/AssetsRefGenerator/releases/tag/v1.2.221
